#pragma once

#define SERVO_PIN_FALLTUER 5
#define SERVO_PIN_AUSSCHIEBER 6

#define SERVO_POS_FALLTUER_OFFEN 170
#define SERVO_POS_FALLTUER_ZU 10

#define SERVO_SPEED_FALLTUER_AUF 2000
#define SERVO_SPEED_FALLTUER_ZU  2000

#define SERVO_POS_AUSSCHIEBER_NORMAL 20
#define SERVO_POS_AUSSCHIEBER_DRAUSSEN 150

#define SERVO_SPEED_AUSSCHIEBER_RAUS 2500
#define SERVO_SPEED_AUSSCHIEBER_REIN 1000

#define MOTOR_KETTE_PIN_DIRECTION 12
#define MOTOR_KETTE_PIN_BRAKE 9
#define MOTOR_KETTE_PIN_SPEED 3

#define MOTOR_BAND_PIN_DIRECTION 13
#define MOTOR_BAND_PIN_BRAKE 8
#define MOTOR_BAND_PIN_SPEED 11

#define BUTTON_PIN 10
